name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Render
        run: |
          # Use curl to trigger the Render deploy hook
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
